# Generated by Django 5.1 on 2026-04-16 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('industry', models.CharField(max_length=255)),
                ('sub_industry', models.CharField(max_length=255)),
                ('company_size', models.CharField(choices=[('small', 'Small (1-50)'), ('medium', 'Medium (51-250)'), ('large', 'Large (251-1000)'), ('enterprise', 'Enterprise (1000+)')], max_length=50)),
                ('annual_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employee_count', models.IntegerField()),
                ('year_established', models.IntegerField()),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=255)),
                ('policy_number', models.CharField(blank=True, default='', max_length=100)),
                ('broker_name', models.CharField(blank=True, default='', max_length=255)),
                ('broker_contact', models.CharField(blank=True, default='', max_length=255)),
                ('coverage_type', models.CharField(max_length=255)),
                ('total_insured_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('risk_rating', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=20)),
                ('previous_claims_count', models.IntegerField(default=0)),
                ('last_assessment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
