# Generated by Django 5.1 on 2026-04-16 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('note', 'Note')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/')),
                ('text_content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='assessments.assessment')),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'ordering': ['-created_at'],
            },
        ),
    ]
